Summary:	Graphviz to LaTeX converter


Name:		dot2tex
Version:	2.8.7
Release:	5
Source0:	%{name}-%{version}.zip
License:	MIT
Group:		Graphics
Url:		https://www.fauskes.net/code/dot2tex/
BuildArch:	noarch
Requires:	python-parsing
Requires:	emacs-auctex
Requires:	graphviz
Suggests:	texlive
BuildRequires:  python-devel

%description
The purpose of dot2tex is to give graphs generated by Graphviz a more
LaTeX friendly look and feel. This is accomplished by converting xdot
output from Graphviz to a series of PSTricks or PGF/TikZ
commands. This approach allows:

* Typesetting labels with LaTeX, allowing mathematical notation.
* Using native PSTricks and PGF/TikZ commands for drawing arrows (optional).
* Using backend specific styles to customize the output

Dot2tex can preprocess graphs using the preview package. Information
about label sizes will be extracted and used to get correctly sized
nodes and edge labels.

%prep
%setup -q

%install
PYTHONDONTWRITEBYTECODE= %__python setup.py install --root=%{buildroot} --record=FILE_LIST
%__chmod -R o-w *.txt LICENSE doc/ examples
%__chmod -R g-w *.txt LICENSE doc/ examples

%clean

%files -f FILE_LIST
%doc *.txt LICENSE doc/* examples/
